Revert "Bug inscriptions scolaires File "/home/cgirard/noethys/DLG_Saisie_inscriptions_scolaires.py", line 349, in __init__ self.ctrl_recherche = OL_Inscriptions_scolaires_2.CTRL_Outils(self, listview=self.ctrl_listview) AttributeError: 'Dialog' object has no attribute 'ctrl_listview' "
This reverts commit 45fa01f9356ca0463a5ff6a41b6a715b502fffee.